// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugyfajslzfxuutdlatdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVneWZhanNsemZ4dXV0ZGxhdGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDIwODYsImV4cCI6MjA2Njg3ODA4Nn0.pG9cEEXw9J3jnNFrLJCHgdsZe3mbTjMGJlZM4gmfyns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});